package io.ark.springboot.core.support.error

enum class ErrorCode {
    FILE_UNSUPPORTED_TYPE,
    FILE_SIZE_EXCEEDED,
    FILE_MISSING,
    FILE_NOT_FOUND,
    FILE_PENDING_UPLOAD,
    FILE_ACCESS_DENIED,
    FILE_UPLOAD_ERROR,
    FILE_DOWNLOAD_ERROR,
    FILE_TOO_MANY_UPLOADS,
    CONTENT_INVALID_LENGTH, // 콘텐츠 길이 오류
    CONTENT_BANNED_WORD, // 금지어 포함 오류
    INVALID_ENUM_VALUE,
    VALIDATION_ERROR,
    INVALID_REQUEST_FORMAT,
    E500,
}
