package io.ark.springboot.core.support.error

enum class ErrorCode {
    USER_NOT_FOUND,
    USER_EMAIL_ALREADY_EXISTS,
    USER_USERNAME_ALREADY_EXISTS,
    FILE_UNSUPPORTED_TYPE,
    FILE_SIZE_EXCEEDED,
    FILE_MISSING,
    FILE_NOT_FOUND,
    FILE_PENDING_UPLOAD,
    FILE_ACCESS_DENIED,
    FILE_UPLOAD_ERROR,
    FILE_DOWNLOAD_ERROR,
    FILE_TOO_MANY_UPLOADS,
    FEED_NOT_FOUND,
    COMMENT_NOT_FOUND,
    CONTENT_INVALID_LENGTH, // 콘텐츠 길이 오류
    CONTENT_BANNED_WORD, // 금지어 포함 오류
    INVALID_FEED_ID,
    INVALID_AUTHOR_ID,
    INVALID_ENUM_VALUE,
    VALIDATION_ERROR,
    INVALID_REQUEST_FORMAT,
    E500,
}
